### ISSUE TITLE
No such directory or file. (Manjaro KDE)

### ISSUE THREAD

**Issue by dakshcs** [RaitaroH/LibreOffice-BreezeDark#6]
I installed icons successfully but when I try to install the theme this is the output - 
`[daksh_s@R53600X ~]$ mv ~/.config/libreoffice/4/user/config/standard.soc ~/.config/libreoffice/4/user/config/standard.soc.back
mv: cannot stat '/home/daksh_s/.config/libreoffice/4/user/config/standard.soc': No such file or directory
`

**Comment by RaitaroH** [comment]
I'm on manjaro too but I do have that, perhaps from my old home. Can you try to just create the folder if you don't have it? Most likely because you never changed the appearance you just don't have that file, even if you have the folder, so is nothing to back up :)
Also do keep in mind that some manual theming as per the images might be preferable :+1:
